baseURL = "https://lzy17.github.io/"
languageCode = "zh-cn"
title = "Joey's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Joey Li"
  description = "Welcome to Joey's Blog"
  github = "Lzy17"
  twitter = "Jozzy83322411"
  linkedin = "zhaoyi-joey-li"
  email = "jozzy.dev@gmail.com"
  url = "https://lzy17.github.io/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "San Diego, CA, US"
  avatar = "https://avatars3.githubusercontent.com/u/36555117?s=460&u=7ed115979d999523eaff4f0fead1d6a33edfdb5c&v=4"

  [[params.links]]
    title = "Link2"
    href = "https://jozzy.dev"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
